### ISSUE TITLE
Node Modules issue on renderer file

### ISSUE THREAD

**Issue by ghost** [lightning-js/solid-demo-app#2]
Hi @chiefcll  , 
There is a NodeModules Error on this particular file 
node_modules/@lightningjs/renderer/dist/src/core/text-rendering/font-face-types/SdfTrFontFace/internal/FontShaper.js"
( Error: points to missing source files)
please look into it

**Comment by chiefcll** [comment]
Thanks - I'll put that into the renderer issues and close out here.
