### ISSUE TITLE
On Webkit 2.22 I'm getting import errors - possible browser incompatibility 

### ISSUE THREAD

**Issue by thorbjornvynne** [lightning-js/solid-demo-app#3]
Running the demo from todays master:

On RDK 20.1 device with Webkit 2.22 browser I'm getting these errors:

[Error] SyntaxError: Unexpected token '.'. import call expects exactly one argument.
	promiseReactionJob

[Error] SyntaxError: Unexpected token '.'. Expected namespace import or import list.
	promiseReactionJob

Works fine on Chrome

**Comment by chiefcll** [comment]
Did you just update to latest - changed driver to main?

**Comment by chiefcll** [comment]
Probably cause we're using type='module' and need to compile the code - will check the vite settings to do that

**Comment by chiefcll** [comment]
OK - download latest - `npm run build`

**Comment by thorbjornvynne** [comment]
Thanks, let me try

**Comment by thorbjornvynne** [comment]
Hi @chiefcll Unfortunately I get the same error. I'll try to find out where this error originates from .

**Comment by chiefcll** [comment]
should be working now - we've tested on rdk 2.24 and 2.4 of wpe
