### ISSUE TITLE
The background is not visible unless I set width and height

### ISSUE THREAD

**Issue by pecoram** [lightning-js/solid-demo-app#4]
https://github.com/lightning-js/solid-demo-app/blob/17c76185b05669863a22804befd9b57320fe0e5c/src/components/Background.jsx#L9

The same situation if I remove the color style or set another color like:  `color: '#000000'`

**Comment by chiefcll** [comment]
Let me know if this issue still exists. Elements should default to width and height of their parent now

**Comment by pecoram** [comment]
This is no longer an issue. I no longer have to set the width and height. 
But without color or with #000000 I can't see the background image, but this is another issue I guess.

**Comment by chiefcll** [comment]
Yes - Solid defaults the color to transparent for nodes. But if you have an Image that you assign a src to after creation, you need to set the color too, otherwise it will be transparent. (It's in the Lightning Solid docs)

**Comment by pecoram** [comment]
yes if color is not set but what about setting color #000000 ?

**Comment by chiefcll** [comment]
https://github.com/lightning-js/solid#color

I think you'd have to set the alpha as well with `#000000ff`

**Comment by pecoram** [comment]
<img width="1289" alt="Screenshot 2023-10-16 alle 16 45 40" src="https://github.com/lightning-js/solid-demo-app/assets/33352553/4eaa27ef-fc0f-452d-9552-ba097d390099">
I've already tried 
`const bgStyles = { alpha, color: "#000000ff"};`

**Comment by chiefcll** [comment]
Do you have the latest? pnpm install - maybe delete your node_modules

<img width="1468" alt="image" src="https://github.com/lightning-js/solid-demo-app/assets/2090941/b9cdcccb-7d28-4ce0-9209-1b143319c8ea">

**Comment by pecoram** [comment]
v0.6.4
you also have to change the line 22 `bg1.color = 0x000000ff;`

**Comment by pecoram** [comment]
have you tried?
