### ISSUE TITLE
Demo app is not working on lg webos smart tv

### ISSUE THREAD

**Issue by bgity** [lightning-js/solid-demo-app#6]
Hi Team

After creating ipk build of demo app, build is not working on smart TV devices. It giving the issue of access denied in console. Please suggest any changes.

**Comment by chiefcll** [comment]
Is the access denied for making API calls? Did you add a tmdb key? And enabled web access?

**Comment by bgity** [comment]
App is working fine on desktop. All api is working fine also I am adding tmdb key.

But after creating IPK file of build and this IPK file running on LG webos smart tv it gives below error

Uncaught SyntaxError: Unexpected token '?'

Check below image

<img width="923" alt="image" src="https://github.com/lightning-js/solid-demo-app/assets/23340102/5f0e5f50-ed4a-42a5-910a-c5c17827f5e7">

**Comment by bgity** [comment]
@chiefcll Please guide to create simple demo app of **hello world** in solidjs that will working on smart tv.

**Comment by chiefcll** [comment]
That is probably from Optional Chaining - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Probably not supported - you'll need to compile the code to ES5 - I haven't spent much time getting this to run on boxes as I have some other priorities. I'll hopefully get to this next week.

**Comment by bgity** [comment]
@chiefcll thank you very much for quick replay

**Comment by chiefcll** [comment]
Let me know if you got this working. It's on my list to get to this in the next 2 weeks on a Tizen device. Did get it working on an rpi 3 with RDK

**Comment by chiefcll** [comment]
Closing - Solid demo app now runs on Chrome >= 49
