### ISSUE TITLE
When tried to launch on TV Using RPi4

### ISSUE THREAD

**Issue by justForusee3** [lightning-js/solid-demo-app#9]
![Screenshot from 2024-01-04 19-11-45](https://github.com/lightning-js/solid-demo-app/assets/125953355/6526a9ad-142e-416b-9858-4f6eba694508)

Getting connection refused.

**Comment by justForusee3** [comment]
using this command .....  curl -H "Authorization: Bearer $token" -d '{"jsonrpc":"2.0","id":"3","method": "org.rdk.RDKShell.1.launch", "params": {"callsign": "testapp", "type":"ResidentApp", "uri":"http://192.168.2.155:8081/?mf=ws%3A%2F%2F0.0.0.0%3A3474%3Fsession%3Drefui%26appId%3Drefui&systemui=true"}}' http://127.0.0.1:9998/jsonrpc

**Comment by chiefcll** [comment]
Did you figure this out? Nothing to do with the app but more of your setup. Seems like you are having trouble connecting to your device or it connecting back to your local machine / demo app - check your networking
